### ISSUE TITLE
My week does not filter for current day

### ISSUE THREAD

**Issue by Daniel-Seifert** [mobileappdevhm20/team-project-team_5#100]
# Bug in a nutshell

Today is friday but the meals from monday are shown.

![image](https://user-images.githubusercontent.com/31901828/86453606-5ae75500-bd1e-11ea-8f26-d4fac77309fa.png)

# Expected behavior

Past meals should be filtered out.

**Comment by Cavvar** [comment]
Tested in emulator by assigning a plan and checking the week view. It was only showing the sunday recipes which should be understandable after 10pm
![grafik](https://user-images.githubusercontent.com/3383908/86520495-3cc84480-be45-11ea-97f2-926f24bdc83a.png)

The app icon is also included but that is something I would like to discuss tomorrow! I'll be merging this PR anyway.
