### ISSUE TITLE
Final presentation

### ISSUE THREAD

**Issue by Daniel-Seifert** [mobileappdevhm20/team-project-team_5#108]
# Description

Create the final presentation.
Following points should be taken into account:

![image](https://user-images.githubusercontent.com/31901828/86456753-d945f600-bd22-11ea-9cc1-0faaa4627c13.png)

**Comment by Cavvar** [comment]
https://docs.google.com/presentation/d/1WoFE4SKFMnFTBZg4nIb6udW9nLksTDbfpL5yhzirJ00/edit?usp=sharing

**Comment by Cavvar** [comment]
- Evolution and Initial Requirements : Toni
- Demo: Martin
- App Architecture: Daniel
- CodeQuality/Development Process/KeyLearnings: Denis

**Comment by Cavvar** [comment]
v1 of presentation is done.
