### ISSUE TITLE
Delete recipe plans

### ISSUE THREAD

**Issue by Daniel-Seifert** [mobileappdevhm20/team-project-team_5#12]
# Story

As an recipe-plan creator I want to be able to delete recipe plans

# Acceptance Criteria

- [x] There is a delete button for recipe plans created by me when I am logged in
- [x] There should be a prompt if I really want to delete the recipe plan after clicking on the delete button

**Comment by Cavvar** [comment]
So deleting is only possible for plans I have created myself. These plans are also stored on my local device. So when deleting it should delete both the plan on my device and on the backend

**Comment by Cavvar** [comment]
With latest commit 437087d146ed4321f3be1e1ff6d76ada85bdab4b added alert dialog when deleting the mealplan
