### ISSUE TITLE
Description for recipe plan

### ISSUE THREAD

**Issue by Daniel-Seifert** [mobileappdevhm20/team-project-team_5#15]
# Story

As a recipe-plan author I want to specify an additional description for my plan to give users more information about my intentions when creating it.

# Acceptance Criteria

- [x] I can set a title for the recipe plan
- [x] I can edit the full-description of my own recipe plans
- [x] I can edit the brief-description (Only one phrase) of my own recipe plans
- [ ] The full-description of the recipe plan is visible when viewing it in detailed mode
- [x] The brief-description of the recipe plan is visible when browsing through all recipe plans

**Comment by Tosaa** [comment]
Show Title and Description of the MealPlan on the Top of the MealPlanDetail view.

**Comment by Tosaa** [comment]
Done
