### ISSUE TITLE
Searching through recipes

### ISSUE THREAD

**Issue by Daniel-Seifert** [mobileappdevhm20/team-project-team_5#19]
# Story

As content creator, i want to select the recipes for the plan fastly. Therefore the creator can filter recipes of the used api, to find the imagined recipe.

# Acceptance Criteria

- [x] There is a way to enter a search phrase in the list of all recipes
- [x] Each search phrase is matched full text against all available recipes (while typing)
- [x] I want the search phrase to be still there after returning from a recipe detail view

**Comment by Tosaa** [comment]
Also adjust the Backend and the recipe repository. 
Try to use an api which loads recipes into the backend.
