### ISSUE TITLE
Show recipe plan details

### ISSUE THREAD

**Issue by Cavvar** [mobileappdevhm20/team-project-team_5#20]
# Story

As a user I want to be able to see the ingredients, cookingtime, recipe and etc. of each recipe I am subscribed to

# Acceptance Criteria

- [ ] There is a button that navigates me to a list of my managed recipe plans
- [ ] When clicking on a recipe plan it shows me all of the connected recipes
- [ ] When clicking on one specific recipe it navigates to a detail page with the relevant data

**Comment by Daniel-Seifert** [comment]
Duplicates #43

**Comment by Daniel-Seifert** [comment]
Duplicates #43
