### ISSUE TITLE
Browsing recipe plans

### ISSUE THREAD

**Issue by Cavvar** [mobileappdevhm20/team-project-team_5#27]
# Story

As the user I want to browse through existing plans, to subscribe one or more of them, or show its details.

# Acceptance Criteria

- [x] A button navigates/enables me to browse through existings plans
- [ ] Clicking on a recipe plan navigates me to its detail page
- [ ] A button adds the recipe plan to my local library
- [ ] If I have clicked on an already subscribed item, the button removes it from my local storage
- [ ] There is an indicator if I am already subscribed to the recipe plan while browsing one

**Comment by Tosaa** [comment]
The functionality is not to assign the mealplan to a week, its more about to save the mealplan localy and it should be shown in the manage view, so a user can assign it then to a calenderweek
