### ISSUE TITLE
Subscribe without an account

### ISSUE THREAD

**Issue by MartinEkman** [mobileappdevhm20/team-project-team_5#37]
# Story

As a user without special conditions, i simply can use the app without an account. Subscribied plans & recipes will be stored localy. 

# Acceptance Criteria

- [ ] No mandatory log in, so i can simply use the app by just open it
- [ ] After entering the app i can quickly subscribe on meal plans or recipes
- [ ] The recipes and meal plans will be stored localy and easy to view.

**Comment by Tosaa** [comment]
when ever the user interacts with the app, the device id will be used as the username. each device is an user and no login is needed for now.
