### ISSUE TITLE
Browse Recipe Plans

### ISSUE THREAD

**Issue by Daniel-Seifert** [mobileappdevhm20/team-project-team_5#55]
Browse all recipe plans

**Comment by Cavvar** [comment]
In my current branch we already have a view similar to our prototype filled with mocked data created by toni. Currently I only am not sure how to load the images into the "card" properly.

**Comment by Cavvar** [comment]
From the prototype:
![grafik](https://user-images.githubusercontent.com/3383908/83241982-f293d980-a19b-11ea-9f0c-dc60c109430c.png)
