### ISSUE TITLE
Assigning meal plan always shows already assigned message

### ISSUE THREAD

**Issue by Daniel-Seifert** [mobileappdevhm20/team-project-team_5#99]
# Bug in a nutshell

This error always appears when assigning a meal plan
![image](https://user-images.githubusercontent.com/31901828/86453294-d5fc3b80-bd1d-11ea-8428-955f73528216.png)

# Expected behavior

Message should not be shown when week is not assigned

**Comment by Daniel-Seifert** [comment]
This is the feedback from sprint 2:

 I am unable to assign a MealPlan to this week

**Comment by Tosaa** [comment]
Also the Weeks of the Year do not match with the Dates which are displayed 

in screenshot: 
* The week did not start on 3.6, it started on 29.6
* The week did not end on 10.6, it ends on 6.7
